### ISSUE TITLE
New frontend crashes on iOS

### ISSUE THREAD

**Issue by jay187** [Hypfer/Valetudo#1232]
When opening the new frontend either with Safari or Chrome under iOS 15.1 the browser crashes after a reload of the page.
I've also cleared the browser cache and website data but this didn't help either.
Using the old frontend still works though.

## To Reproduce

1. Open Valetudo Web UI via iPhone (Safari / Chrome)
2. Wait 
3. No interaction possible -> Crash

### Screenshots

[<img src="https://user-images.githubusercontent.com/3536728/143068015-9f977c4d-b470-4fa3-aff4-84d23dcfe329.jpeg" width=250>](https://user-images.githubusercontent.com/3536728/143068015-9f977c4d-b470-4fa3-aff4-84d23dcfe329.jpeg)

### Vacuum Model

Dreame D9

### Valetudo Version

2021.11.1

## Expected behavior

Frontend shouldn't crash.

**Comment by Hypfer** [comment]
Unfortunately due to Apple being Apple, there is no way of debugging this without spending thousands of dollars for apple-certified hardware.
The code itself is valid and works fine on all platforms that aren't Apple so it's not a bug in Valetudo.

Anyways, I can't do anything about that so I'll leave this open for someone willing to pay the Apple tax to figure out.

**Comment by Hypfer** [comment]
Sidenote:

The only map-related change between 2021.11.0 and 2021.11.1 was that there can now be multiple path entities on dreame resulting in multiple svgs being drawn onto the map canvas.
If someone decides to pick this up that might be a good place to start looking.

**Comment by jay187** [comment]
@Hypfer Thanks for the quick reply. Just some more context: It seems like an iOS 15 problem. On my other iPhone running iOS 14 the frontend works as expected.

**Comment by maciejtarmas** [comment]
Can confirm. Looks like more complex maps crash Safari on iOS. Same map on Safari on macOS causes it to display “This page is slowing down Safari” message. Seems that some maps cause a resource usage spike when being drawn.

Source: my 2 Dreame D9 robots. One works, and one crashes Safari. Same map works fine on Firefox though.

Haven’t really started looking into it, so I haven’t filed a bug report myself.

**Comment by Hypfer** [comment]
@maciejtarmas 
> Same map works fine on Firefox though.

Firefox on iOS? That is _very_ strange as all browsers on iOS are using the Safari Webkit implementation as their rendering framework meaning that there only is Safari on iOS.

Why would it crash Safari Safari but not Firefox Safari?

See: https://en.wikipedia.org/wiki/Firefox_for_iOS
>2.5.6 Apps that browse the web must use the appropriate WebKit framework and WebKit Javascript.

**Comment by jay187** [comment]
@Hypfer It's working now. Did not change anything on the phone but I did vaccum today. Maybe due to that and the fact the map has new data it's working now? So this might be a only an issue after the upgrade when no run was made?

**Comment by Hypfer** [comment]
That very much sounds like a bug in Safari

**Comment by maciejtarmas** [comment]
@Hypfer No, no. I was talking about the desktop version of Firefox. I won’t be home until later this week so I can’t check if starting a new clean up fixes this. That’s some Safari bug obviously, but I’ll take a look at memory consumption and whatnot.

**Comment by fox34** [comment]
> @Hypfer It's working now. Did not change anything on the phone but I did vaccum today. Maybe due to that and the fact the map has new data it's working now? So this might be a only an issue after the upgrade when no run was made?

Can confirm that the crash is somewhat map-state-dependent. Safari on iOS 15.1 crashed yesterday while the robot was in idle mode. After starting the robot, Safari did not crash any more.

**Comment by michalsliwa** [comment]
Same problem here, after checking with Safari Web Inspector i see error:
Unrecognized Content-Security-Policy directive 'worker-src'.

% curl -sI http://x.x.x.x | grep Content-Security-Policy | tr ' ' '\n'
Content-Security-Policy:
worker-src
'self';

Not sure if it's related, but apparently Safari does not support this directive

**Comment by Hypfer** [comment]
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/54219

The `Unrecognized Content-Security-Policy directive 'worker-src'` is normal and should not interfere with anything

**Comment by maciejtarmas** [comment]
The problem seems to be related to rendering the robot's path on the map by Safari.

I sent the robot that was crashing Safari for a small spot clean and the main UI started loading on iOS, but resizing the map crashed the page again.

Note that loading the map editor @ http://robot_address/#/robot/edit_map does not cause the UI to crash and zooming and moving the map around is smooth.

I tried the current version of Safari Technology Preview on a Mac (reports as Safari 15.4, current version is 15.1) and it seems to work better, not causing huge CPU spikes, but it's still not smooth when there is the robot's path overlaid on the map. Additionally, the path is extremely blurred to a point where it's completely useless, much worse than current Safari.

It's a Safari thing for sure, but I wonder if something can be done with it.

@Hypfer , would it be possible to implement a path display on/off toggle for the UI? This way we could confirm if path rendering is the problem.

**Comment by lukaswimmer** [comment]
Valetudo 2021.12.1 works on Safari in the newly released updates of iOS 15.2 and macOS 12.1.

**Comment by maciejtarmas** [comment]
> Valetudo 2021.12.1 works on Safari in the newly released updates of iOS 15.2 and macOS 12.1.

No.

![B116B266-7B38-4124-A609-58E8959BAC25](https://user-images.githubusercontent.com/3435387/146045678-50399c19-4e61-42b7-99f7-58e86f4ad79e.png)

**Comment by wienans** [comment]
For me it also looks like that it is only happening if the path is rendered. Maybe it is possible to deactivate path rendering?

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/actions/runs/1584687882

This build renders paths as low-res pngs on apple mobile devices.
Please try and report back

**Comment by Findus23** [comment]
I tried out the `feat_apple_png_path` branch and it seems to be working (as in the site doesn't crash on my iPad Air 2). It's still a bit slow, but I blame that on the quite old device.
Only issue is that the line drawn is really quite blurry, but it's still a huge improvement to before (and I assume without any disadvantage for non-safari-users.
![IMG_0722](https://user-images.githubusercontent.com/6266037/146639773-a4426adb-1baf-449f-9690-63909b08c140.PNG)

**Comment by wienans** [comment]
Actually I didn’t had time to test the branch but now it seems to work for me at least with the official release.
![2C983DB2-F153-4DF4-9205-7F7C5DCAD94E](https://user-images.githubusercontent.com/40465543/146642772-aff9b6c6-caf4-4098-86a8-e67bd9b58d93.png)
Between I updated to iOS 15.2 but didn’t checked if the issue was occurring directly after the update.

**Comment by Hypfer** [comment]
What about `feat_consolidated_paths`?

Build: https://github.com/Hypfer/Valetudo/actions/runs/1596132463

**Comment by Hypfer** [comment]
As far as I can tell, Apple "fixed" this crash in iOS 15.2

The path looks horrible likely due to a very low render resolution, but at least safari doesn't crash anymore.

**Comment by maciejtarmas** [comment]
> As far as I can tell, Apple "fixed" this crash in iOS 15.2


No. The screenshot is from iOS 15.2

https://github.com/Hypfer/Valetudo/issues/1232#issuecomment-993791897

**Comment by sstadlberger** [comment]
> As far as I can tell, Apple "fixed" this crash in iOS 15.2
> 
> The path looks horrible likely due to a very low render resolution, but at least safari doesn't crash anymore.

I can confirm that the crash is still present in iOS 15.2. It’s not always fully reproducible as it depends on the actual path the vacuum took.

By the way, the paths always looked that pixelated for me in Safari, that was even before Safari started crashing.

I think that Safari will be fixed in one of the next releases, I tried the Safari Technology Preview and it works there without any problems while the regular Safari crashes. 

And thank you for making this great piece of software!

**Comment by sstadlberger** [comment]
> What about `feat_consolidated_paths`?
> 
> Build: https://github.com/Hypfer/Valetudo/actions/runs/1596132463

Sorry for the late response. I tried it out today so it's still a bit early to be sure if this solves the issue, but so far it looks promising. Thanks again for the support!

**Comment by danielk117** [comment]
> I can confirm that the crash is still present in iOS 15.2. It’s not always fully reproducible as it depends on the actual path the vacuum took.

iOS 15.2 and when i try to zoom, while it is cleaning, the webapp crashes. But only on my Dreame Z10. 
On my Roborock S5 this doesn't happen.

> By the way, the paths always looked that pixelated for me in Safari, that was even before Safari started crashing.

Same for me. 

> What about feat_consolidated_paths?
>
> Build: https://github.com/Hypfer/Valetudo/actions/runs/1596132463

I will give a try later.

**Comment by lukaswimmer** [comment]
The shortly posted build works always fine on my D9. iOS 15.2 is used. 

I don’t know if it helps, but I realised the following: In release 2021.11.0 the renderer was changed. The path in the new UI of 2021.10.0 did not look pixelated, while it was pixelated in the old UI. That behaviour changed with 2021.11.0 where all UI paths were pixelated. 

2021.10.0 on iOS 15.2:
![5B3EA232-A5A8-48FB-A9B3-A87A874FF9CC](https://user-images.githubusercontent.com/6631057/147741400-e24c6133-5121-4cd9-bb6b-9968dee0639c.jpeg)

2021.12.1 on iOS 15.2:
![87D1380B-EB36-4F34-B73E-E1B024F16908](https://user-images.githubusercontent.com/6631057/147741434-121c49e2-4fd7-4cab-af33-7d7985b75e9a.jpeg)

**Comment by danielk117** [comment]
> What about `feat_consolidated_paths`?
> 
> Build: https://github.com/Hypfer/Valetudo/actions/runs/1596132463

I replaced the binary. Seems to fix the crashes, but the path is still looks horrible... 😞 

![grafik](https://user-images.githubusercontent.com/36566093/147783895-d0f4792b-9800-4095-8192-d35e4776f01a.png)

**Comment by maciejtarmas** [comment]
2022.01.0 doesn't crash Safari on iOS anymore and doesn't cause CPU spikes on macOS on current Safari Version 15.2 (17612.3.6.1.6) and Safari Technology Preview Release 137 (Safari 15.4, WebKit 17613.1.11.8). The path still looks like crap no matter what version of Safari or platform is used, but I can live with it. Thanks 👍

Again, could someone running GNOME Linux Desktop check how the UI is rendered on GNOME Web? Both Safari and GNOME Web use the WebKit engine, so we could at least check if the bug is specific to Safari or is there something wrong with WebKit, so we can file a bug report in an appropriate place.

Screenshot taken on an iPad Something running iOS 15.
![Untitled](https://user-images.githubusercontent.com/3435387/147835138-ec5c48c6-a444-4228-b141-f786c55af6d4.png)
2

**Comment by Findus23** [comment]
> Again, could someone running GNOME Linux Desktop check how the UI is rendered by GNOME Web?

Both GNOME web (41.3) and Konqueror (21.08.2) are displaying the page (on 2022.01.0) perfectly fine and look identical to Firefox.

**Comment by lukaswimmer** [comment]
In the recently released Safari Techology Preview 142, the blurred lines are normal lines again. So it seems that the bug could be solved by Apple in one of the next official releases.

**Comment by lukaswimmer** [comment]
Path looks normal again in iOS 16 beta.
