### ISSUE TITLE
Frontend stop responding after a few hours

### ISSUE THREAD

**Issue by abrioy** [Hypfer/Valetudo#1498]
## Describe the bug

I installed Valetudo a few weeks back and it worked fine for a few hours. Since then, when I access the Valetudo front end,  controls and map fail to load.

I first had the problem on version 2022.03.0, it's still happening with 2022.05.1

Reinstalling the full dustbuilder image fixed the problem for a few hours, and then it happened again.

The vacuum is working fine using the buttons, I can still connect with ssh, access the front-end and swagger. It take a long time to connect to wifi after a reboot.

I tried calling a few endpoints with swagger and they seem to be working.

I don't know what to try next, any help would be appreciated :) 

PS : there is one sentence I don't fully understand in the rooting instructions 
> If you see that MOTD, the rooting procedure was successful. However, you’re not done yet. As there are two system partitions, you have to repeat the download and install procedure a second time.
Maybe it has something to do with my problem, but I didn't do anything about the second partition (because I don't know what to do) 

## To Reproduce

- I followed all instructions this page: https://valetudo.cloud/pages/general/rooting-instructions.html
- Valetudo was working fine, I used the vaccum, created a map, setup mqtt and HA
- The next day when I opened Valeduto it wasn't working properly

### Screenshots

![image](https://user-images.githubusercontent.com/7620043/167926618-3ae1171c-0cf9-4d41-b6eb-015b41d950a5.png)

### Vacuum Model

Dreame Z10 pro

## Additional context

I could only get info level logging because the page crashes when I switch to debug
```
2022-05-11T19:06:32.083Z info  Got token from handshake: XXXX
2022-05-11T19:06:37.388Z info  Got an expired token. Changing to new
2022-05-11T19:06:37.391Z info  Got token from handshake: XXXX
2022-05-11T19:06:38.691Z warn  Unable to reach vacuum. Giving up after 100 tries
```
It tries to get a token 10 times before giving up.
I don't know if it's supposed to be this way but the token is always the same. It looks like it never actually gets refreshed

**Comment by Hypfer** [comment]
This seems to be a support request, which will require first-level support question ping-pong.
Due to time constraints, I am unable to provide that.
Issues should only be opened for known bugs. See also http://www.catb.org/~esr/faqs/smart-questions#idm368


The issue you're facing is likely some kind of configuration or install error. To fix such things, factory reset and start from the beginning. Because we're building firmware images that always are in a known good state and also because the hardware is always the same, it is unlikely to impossible that what you're experiencing is a bug in the code, given that the exact same thing works on multiple hundred other robots.

Thank you for your understanding
