### ISSUE TITLE
FR: Home Assistant missing trigger/condition for error message

### ISSUE THREAD

**Issue by haxney** [Hypfer/Valetudo#1613]
## Objective

I would like to set up an automation which notifies my phone when the vacuum encounters an error. The plus sign button in the `Automations` section the device page for the vacuum in Home Assistant lists multiple options for triggering on various events, but it lacks one for the error status changing

## To Reproduce

1. Install Valetudo
2. Link it to Home Assistant via MQTT
3. Visit the device page
4. Click the "Create automation with device" button
5. Observe that there is no trigger or condition on the error message.

### Screenshots

Other trigger options, status message not present:

![robot_options](https://user-images.githubusercontent.com/88132/195939403-ebf141b9-ece8-4aea-aa02-b7d89f2b07b2.png)

### Vacuum Model
Dreame D9 pro

### Valetudo Version
2022.09.0

## Expected behavior

There should be a trigger for "error message changed", and condition for "error message is (not) empty."

## Additional context

I was able to make it work with template-specified conditions and actions as follows:

```
alias: Vacuum error notification
description: ''
trigger:
  - platform: state
    entity_id:
      - sensor.valetudo_belovedhandmadeibis_error_description
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.valetudo_belovedhandmadeibis_error_description
        state: ''
action:
  - device_id: xxxxxxxxxxx
    domain: mobile_app
    type: notify
    message: >-
      Error in vacuum: {{
      states("sensor.valetudo_belovedhandmadeibis_error_description") }}
    title: Vacuum error
mode: single
```

I have verified that this works, but it would be more convenient if this functionality was more directly exposed in the UI.

**Comment by Hypfer** [comment]
What can Valetudo do about this?

**Comment by haxney** [comment]
I would have thought that it was something in the capabilities announcement that Valetudo broadcasts during MQTT autodiscovery.

**Comment by Hypfer** [comment]
Sounds like a reasonable need, yes. 
It would've been great though if you'd've did research on the topic before opening this issue.
This "hey dev make thing work kthxbye" is pretty annoying mildly put.

You're as able as anyone else to figure out if it is possible to enhance the mqtt annoucements so that "in error" appears in that dialog in home assistant. Researching that requires no knowledge of the Valetudo codebase.

**Comment by haxney** [comment]
I've never worked with the Home Assistant API, nor Valetudo.

I can understand if this is not a priority for current development, but there's no need to get hostile over a feature request.

**Comment by Hypfer** [comment]
There is need to call out people being lazy and trying to get other members of the foss community to work for them.
All you'd have to do is to read the Home Assistant Docs. You can do that. You're a senior software developer.
There is literally difference between me and you there. We'd both have to do exactly the same.

Yet you instead decide to open a Bug report(!) even though this is no bug and it clearly even tells you that you should not be doing so:
![image](https://user-images.githubusercontent.com/974410/196351022-ec7b3256-f8a0-400f-a11d-827fcc0e2259.png)

"Why is there no feature request template?" one might ask.
Well the answer is simple:
Because those usually turn out exactly like this. Lazy "Hey dev do this. Kthxbye" even though it would be perfectly possible for the author to provide more support than just the idea. But they won't because they don't care.
Still, they somehow always feel entitled about it.

You're in the wrong here.
Drop the entitlement and leave
