### ISSUE TITLE
Locked out of web server but access through ssh

### ISSUE THREAD

**Issue by matt8707** [Hypfer/Valetudo#435]
Generated a long password and now I'm locked out of the web interface. Is there some way to reset credentials through ssh?

**EDIT:**
`vi /mnt/data/valetudo/config.json`
Now see that my password was cut short from 65 to 63 characters

Maybe some kind of protection or at least a note to prevent this?

**Comment by rumpeltux** [comment]
This is from client/settings-access-control.html
You cannot enter more than 63 characters. And you should notice since no more placeholders are placed.
However this limit seems somewhat arbitrary, so we might just remove it?

The wifi dialog has the same issue. There the 63 character limit is actually correct.
