### ISSUE TITLE
No Map Data

### ISSUE THREAD

**Issue by rpetteruti** [Hypfer/Valetudo#466]
## To Reproduce

1. Go to 'the ip of the xiaomi vacuum with a browser'
2. Click on 'map button'
3. See "no map data"

### Vacuum Model

Gen1

### Valetudo Version

0.4.0

### User-Agent

Firefox 74.0
## Additional context

I've let the vacuum to do more than one complete clean of the house in order to let it build the map without luck.

**Comment by rumpeltux** [comment]
This doesn’t sound like a bug in Valetudo. I hope you can understand that we cannot provide individual support for issues not directly related to the Valetudo software.
You can, however, potentially ask for help on [roboter-forum.com](https://www.roboter-forum.com/index.php?thread/29822-valetudo-alternatives-cloudfreies-webinterface-ohne-dustcloud-mit-livemap-auf-de/) (since the forum is in German you may want to use a translation tool before posting your question there).
