### ISSUE TITLE
After reset from the robot no timers work

### ISSUE THREAD

**Issue by HHenning0815** [Hypfer/Valetudo#473]
Hello,

After a reset of roborock s5 and reinstallation of valetudo the timers not working.
the date is not correct even after i set the ip of my fritz box as ntp server. he minutes are correct but hours are 1 to 5 hours before right time - even after I reset to utc and back cet time. The Berlin timezone is not selected (has an "a" in dialog) via ssh - amsterdam is selectable.
But even if I create new timer with delay of hours (every day different amount of hours), the cleaner will not start automaticly.

What can I do to find out what the problem is?

**Comment by rumpeltux** [comment]
This doesn’t sound like a bug in Valetudo. I hope you can understand that we cannot provide individual support for issues not directly related to the Valetudo software.
You can, however, potentially ask for help on [roboter-forum.com](https://www.roboter-forum.com/index.php?thread/29822-valetudo-alternatives-cloudfreies-webinterface-ohne-dustcloud-mit-livemap-auf-de/) (since the forum is in German you may want to use a translation tool before posting your question there).
