### ISSUE TITLE
Connection with wifi lost after flash

### ISSUE THREAD

**Issue by DLI312** [Hypfer/Valetudo#481]
Hello,

I just flashed the firmware v11_001782.fullos.pkg to my S5 vacuum.  Looked to be working all fine but after the reboot I couldn't access the vacuum via the browsers IP 192.168.X.X that I used during the flashing process. 

I can't find the vacuum in the router page as well, even after some reboots. It seems like with the flash it dropped the connection and when I directly connect to the vacuum via wifi I try to access it by using the IP-adress 192.168.8.33. I can't find a solution for this problem. Mi Home is also not finding the device which seems obvious to me. 

Anyone suggestions? Factory reset and retry the flashing process?

**Comment by Hypfer** [comment]
This doesn’t sound like a bug in Valetudo. I hope you can understand that we cannot provide individual support for issues not directly related to the Valetudo software.
You can, however, potentially ask for help on [roboter-forum.com](https://www.roboter-forum.com/index.php?thread/29822-valetudo-alternatives-cloudfreies-webinterface-ohne-dustcloud-mit-livemap-auf-de/) (since the forum is in German you may want to use a translation tool before posting your question there).
