### ISSUE TITLE
Map has rotated every time a zoned cleanup is run

### ISSUE THREAD

**Issue by scsmartt** [Hypfer/Valetudo#525]
I have The gen1 roborock with zones setup and working great but every time I run a zoned cleanup with multiple zones, the map has rotated. I’m not initiated a full cleanup because I know that this resets the map. Is there any other reason that the map would rotate on its own?

**Comment by Hypfer** [comment]
This doesn’t sound like a bug in Valetudo. I hope you can understand that we cannot provide individual support for issues not directly related to the Valetudo software.
You can, however, potentially ask for help on [roboter-forum.com](https://www.roboter-forum.com/index.php?thread/29822-valetudo-alternatives-cloudfreies-webinterface-ohne-dustcloud-mit-livemap-auf-de/) (since the forum is in German you may want to use a translation tool before posting your question there).
