### ISSUE TITLE
Virtual walls are rotated after saving

### ISSUE THREAD

**Issue by Hacki1111** [Hypfer/Valetudo#530]
The map and the zones are working fine on my vacuum with valetudo.
But I keep having issues with my carpets and virtual walls.
The robot should drive around the carpets so I have to set virtual walls around the carpets.
But some walls are rotated after saving. Where can be the problem?

Before I saved the setting:
![Bildschirmfoto 2020-06-04 um 14 35 01](https://user-images.githubusercontent.com/33983958/83758193-edd69600-a671-11ea-91c1-c31c20be9afa.png)

After saving:
![Bildschirmfoto 2020-06-04 um 14 35 16](https://user-images.githubusercontent.com/33983958/83758230-0181fc80-a672-11ea-812d-d676b1eea789.png)

**Comment by Hypfer** [comment]
If you're reporting a bug, please use the bug report template.

![image](https://user-images.githubusercontent.com/974410/83758787-e368cc00-a672-11ea-881c-c60bb4096f1b.png)
![image](https://user-images.githubusercontent.com/974410/83758800-e9f74380-a672-11ea-84d8-66bff2752176.png)
![image](https://user-images.githubusercontent.com/974410/83758806-ecf23400-a672-11ea-8016-83bcebc313d4.png)

By answering the questions in that template, you're making this a lot easier for everyone.

This issue is fixed in 6724e555 which is included in `0.5.2`.

Since you haven't used the template, I have no idea which version you're running but it's most likely not `0.5.2`

**Comment by Hacki1111** [comment]
I will try 0.5.2, still using 0.5.1.
And I will do it better next time. Thanks a lot!
