### ISSUE TITLE
Rework REST API

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#551]
Proper routes. No routes named after miio commands.
Proper verbs. No PUT request to GET something.

Etc.

Utilizing everything introduced with #544

**Comment by r1sim** [comment]
While documenting the API I noticed some things that could be changed while refactoring the API.

## Combine Endpoints

There are some endpoints that can be unified to one endpoint with multiple possible operations:

| Old Endpoints                                                       | New Endpoint                                                           |
| ------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| `GET /clean_summary` &  `PUT /clean_record`                         | `GET /runs` & `GET /runs/:runId`                                       |
| `DELETE /delete_dnd`, `GET /get_dnd` & `POST /set_dnd`              | `GET /dnd` & `DELETE /dnd` & `PUT /dnd`                                |
| `GET /get_timezone` & `POST /set_timezone`                          | `GET /timezone`& `POST /timezone`                                      |
| `PUT /start_cleaning`,  `PUT /pause_cleaning`, `PUT /stop_cleaning` | `PUT /cleaning_status` (More details in "Bodies that should be added") |
| `PUT /set_sound_volume` & `GET /get_sound_volume`                   | `PUT /sound_volume` & `GET /sound_volume`                              |
| `PUT /test_sound_volume`                                            | `GET /test_sound_volume`                                               |
| `PUT /set_ssh_keys` & `GET /get_ssh_keys`                           | `PUT /ssh_keys` & `GET /ssh_keys`                                      |
| `PUT /find_robot`                                                   | `GET /find_robot`                                                      |
| `PUT /drive_home`                                                   | `GET /drive_home`                                                      |
| `PUT /start_manual_control`                                         | `GET /start_manual_control`                                            |
| `PUT /stop_manual_control`                                          | `GET /stop_manual_control`                                             |
| `GET /get_carpet_mode` & `PUT /set_carpet_mode`                     | `GET /carpet_mode` & `PUT /get_carpet_mode`                            |

## 

## Bodies that should be added



### `PUT /cleaning_status`

This endpoint shall be used to unify all those cleaning action endpoints.

Examples:

**Start Full Cleanup**

```json
{
    "action": "full_cleanup"
}
```

**Pause Cleanup**

```json
{
    "action": "pause_cleanup"
}
```

**Stop Cleanup**

```json
{
    "action": "stop_cleanup"
}
```

**Spot Cleanup**

```json
{
    "action": "spot_cleanup"
}
```

**Start Cleanup by Coords**

```json
{
    "action": "full_cleanup",
    "coords": []
}
```

**Start Cleanup by Zone ID**

```json
{
    "action": "full_cleanup",
    "zone_id": 123
}
```

**Start Cleanup by Segments**

```json
{
    "action": "full_cleanup",
    "segments": []
}
```



## Bodies that should be modified

### `GET /state`

This endpoint currently returns this kind of body:

```json
[
  {
    "__class": "StatusStateAttribute",
    "metaData": {},
    "value": "docked",
    "flag": "none"
  },
  {
    "__class": "FanSpeedStateAttribute",
    "metaData": {},
    "value": "high"
  },
  {
    "__class": "BatteryStateAttribute",
    "metaData": {},
    "level": 100,
    "flag": "charged"
  },
  {
    "__class": "LatestCleanupStatisticsAttribute",
    "metaData": {},
    "type": "area",
    "value": 373025
  },
  {
    "__class": "LatestCleanupStatisticsAttribute",
    "metaData": {},
    "type": "duration",
    "value": 2628
  },
  {
    "__class": "PersistentMapSettingStateAttribute",
    "metaData": {},
    "value": "enabled"
  }
]
```

I don't think it is good to send this data in an array since the objects don't have the same structure. I suggest something like this:

```json
{
    "statusState": {
        "value": "docked",
        "flag": "none"
    },
    "fanSpeed": {
        "flag": "high"
    },
    "batteryState": {
        "level": 100,
        "flag": "charged"
    },
    "latestCleanup": {
        "area": 373025,
        "duration": 2628
    },
    "persistentMapEnabled": true
}
```

### `GET /timezone`

This endpoint currently returns just a plain text string. I think a json body would be more appropriate. I suggest this response body:

```json
{
    "timezone": "Europe/Berlin"
}
```

### `POST /timezone`

The request payload currently looks like this:

```json
{
  "new_zone": "string"
}
```

I think that this payload should match the payload returned by `GET /timezone`. Therefore I'd rename `new_zone` to `timezone`

### `GET /get_sound_volume`

This endpoint currently returns just a plain text string. I think a json body would be more appropriate. I suggest this response body:

```json
{
    "volume": 100
}
```

## Endpoints that should be added

### `DELETE /zones/:zoneId`

The endpoint to create new zones currently deletes all zones that are not in the request payload. I think that this endpoint should only create zones. We should add a seperate endpoint to delete zones.
