### ISSUE TITLE
Unable to flash valetudo on newly bought gen1 xiaomi vacuum

### ISSUE THREAD

**Issue by thrasheri** [Hypfer/Valetudo#595]
I bought a second gen1 xiaomi vacuum for downstairs and I'm unable to install valetudo because I receive an error "Unable to parse message payload". Others with similar issue did a factory reset to older firmware and got valetudo installed. When I do a factory reset the mi home app says firmware up to date. (v. 3.5.4_004010). Is there a way to downgrade the firmware to get the valetudo installed?

**Comment by Hypfer** [comment]
1) This issue tracker is _not_ for support requests.
2) Your issue is mentioned in [the docs](https://valetudo.cloud/pages/knowledge_base/supported-roborock-devices.html#gen-1)

You will want to follow [this](https://www.youtube.com/playlist?list=PL9PoaNtZCJRZc61c792VCr_I6jQK_IdSb) guide on how to root that thing.
