### ISSUE TITLE
Is the "Xiaomi Mi Robot Vacuum Mop Pro" supported?

### ISSUE THREAD

**Issue by T-vK** [Hypfer/Valetudo#615]
https://www.amazon.de/dp/B085BPCV7W 

I can't find the model number anywhere, but it looks very similar to the SDJQR02RR, but can do mopping on top of vacuuming. 

I'm just wondering if that model can be rooted, if Valetudo runs on it and if mopping is supported.

**Comment by Hypfer** [comment]
Hi there,

your issue has been closed, because it is either a support request or something else that would usually be handled by 1st level support.

Since this is not a commercial project, but rather just something I've built for myself and then shared with the world for free, I really can't provide said support.


Therefore, please direct this request somewhere else, where other users might be able to help you.
The Telegram group would be one option but certainly isn't the only one.


Thank you for understanding as well as your interest in the project.
