### ISSUE TITLE
Call command or script by event

### ISSUE THREAD

**Issue by seeers** [Hypfer/Valetudo#616]
I have a suggestion. It would be nice if you could start simple scripts based on events.
e.g. when it starts or is done send a curl command to a SmartHome software without using mqtt.

Is there a way to do that? 

Thank you!

**Comment by Hypfer** [comment]
Hi there,

your issue has been closed, because it is either a support request or something else that would usually be handled by 1st level support.

Since this is not a commercial project, but rather just something I've built for myself and then shared with the world for free, I really can't provide said support.


Therefore, please direct this request somewhere else, where other users might be able to help you.
The Telegram group would be one option but certainly isn't the only one.


Thank you for understanding as well as your interest in the project.
