### ISSUE TITLE
No menu to enable or select mopping

### ISSUE THREAD

**Issue by codingstube** [Hypfer/Valetudo#619]
Hi,

I am not really sure. Currently I've build the actually version of valetudo, but I am missing in the main menu the options for mopping. 

I thought I have seen this in previous versions?

Thanks

**Comment by Hypfer** [comment]
It's the "off" setting.

Also, please don't use this issue tracker for support requests.

**Comment by codingstube** [comment]
Sorry I dont get it. 
I searched the settings but I dont find any option to turn it off or on?!

**Comment by rumpeltux** [comment]
Mopping is automatically enabled when a mop and water tank is present and disabled otherwise.
If water tank but not dustbin is installed, Valetudo will disable vacuuming and use the mop-only mode.

Note the functionality is currently broken, but it’s fixed in https://github.com/Hypfer/Valetudo/pull/608
