### ISSUE TITLE
Xiaomi MiJia 1C (general) Support

### ISSUE THREAD

**Issue by 00lex** [Hypfer/Valetudo#625]
Hi all! What a great project! Kudos! 

Im coming from a Roomba with a esp but its finished after years.
Unfortunately i have not so many time because of offspring to find a s5 which is manufactured at the 5th full moon in the year of a bunny or for a s50 max which has to be disassemble to get root. 
so I decide to get a 1c because there is support since the last update. 

my problem is where to start. can someone please write 2-3 sentences for a beginner?

thank you!

**Comment by Hypfer** [comment]
Hi there,

your issue has been closed, because it is either a support request or something else that would usually be handled by 1st level support.

Since this is not a commercial project, but rather just something I've built for myself and then shared with the world for free, I really can't provide said support.


Therefore, please direct this request somewhere else, where other users might be able to help you.
The Telegram group would be one option but certainly isn't the only one.


Thank you for understanding as well as your interest in the project.
