### ISSUE TITLE
Valetudo crashed every night / MQTT to Home Assistant lost

### ISSUE THREAD

**Issue by Bleala** [Hypfer/Valetudo#644]
Hey there,

i'm having a problem with Valetudo since a few days, although i didn't change anything (wasn't on the vacuum with SSH, last time was when i was flashing valetudo on it).

Every night at three o'clock my Roborock S6 loses the MQTT connection to Home Assistant and when i'm trying access the webinterface, the browser is only loading the site, but nothing else happens.
The vacuum is still connected to my Wifi - the little LED on the Roborock is lighting and i can see him in my routers webinterface.

I also checked the valetudo.log file, just infos and no errors.

Control the vacuum with the normal buttons is working fine and after a reboot it also connects again to my MQTT broker and the webinterface is reachable again (until three o'clock am).

Did anyone had the same problem or does anyone has a solution?

Cheers

**Comment by Hypfer** [comment]
Hi there,

your issue has been closed, because it is either a support request or something else that would usually be handled by 1st level support.

Since this is not a commercial project, but rather just something I've built for myself and then shared with the world for free, I really can't provide said support.


Therefore, please direct this request somewhere else, where other users might be able to help you.
The Telegram group would be one option but certainly isn't the only one.


Thank you for understanding as well as your interest in the project.
