### ISSUE TITLE
Save different maps

### ISSUE THREAD

**Issue by Jans89** [Hypfer/Valetudo#660]
Hello,
Is it possible to save different maps?
We use the robot on two floors.

The first time we let clean him on the 1st floor, where the charging station is not located, he deleted the first map. After the cleaning process, he wandered around for minutes looking for the charging station. When I brought it back to the charging station on the ground floor, the map from the ground floor was restored, but the map from the first floor was deleted.
Is there a solution for this?

**Comment by Hypfer** [comment]
Hi there,

your issue has been closed, because it is either a support request or something else that would usually be handled by 1st level support.

Since this is not a commercial project, but rather just something I've built for myself and then shared with the world for free, I really can't provide said support.


Therefore, please direct this request somewhere else, where other users might be able to help you.
The Telegram group would be one option but certainly isn't the only one.


Thank you for understanding as well as your interest in the project.
