### ISSUE TITLE
valetudo 2021.02.0 broken update via RoboRock Control Center - missing file?

### ISSUE THREAD

**Issue by pejotigrek** [Hypfer/Valetudo#710]
## Describe the bug

I use RoboRock Control Center for doing updates as it's the easiest way for me and it worked until the 2021.02.0 version - 2021.01.1 was installed correctly, but now, when trying to update to 2021.02.0 I am having an issue - looks like there is a file missing in the repository [I tried to enter the url directly and indeed - file is not found].

error from log:
```
GET: failed -> Error transferring https://github.com/Hypfer/Valetudo/raw/master/deployment/valetudo.conf - server replied: Not Found
```

## To Reproduce

1. run RoboRock Control Center [version: 0.8.8 - 25.01.2020]
2. goto Valetudo/Install
3. choose latest version from the list & click "Install"

### Screenshots

![image](https://user-images.githubusercontent.com/10796588/108759980-5beb2200-754d-11eb-9dc2-cfaf4e8ebf10.png)

### Vacuum Model

Xiaomi Mi SDJQR02RR [Xiaomi Mija Mi Robot Gen1]

### Valetudo Version

2021.01.1 ->  2021.02.0
## Expected behavior

I am aware that this is not a RoboRock Control Center repository, but knowing that this way of updating worked until the last version - I am thinking that "something went wrong" and accidentally the file needed for update went missing, so I'd like to bring it back please ;)

**Comment by Hypfer** [comment]
It was removed on purpose.

**Comment by pejotigrek** [comment]
> It was removed on purpose.

so now the only way of update is doing it "by hand"? :(

**Comment by Hypfer** [comment]
> I am aware that this is not a RoboRock Control Center repository

Then you're also aware that this is the wrong place for this problem. Why still do it?

> so now the only way of update is doing it "by hand"? :(

The only way to update is to follow the official upgrade instructions of which RRCC isn't part of.

> accidentally the file needed for update went missing

Nope. There are a few reasons for why they've been removed

- They were outdated and afaik didn't produce a working Valetudo Install
- They were specific to some roborock models, however Valetudo runs on many more vacuums so it doesn't make sense to have that here
- As far as I was aware, nothing was using those


In any case it's a good thing that this broke the Valetudo Install Feature of RRCC because this way people won't complain about issues caused by an invalid install procedure.

The recommended way to install and upgrade Valetudo on the robots that have previously been supported by RRCC is to follow the official instructions here: https://valetudo.cloud/pages/installation/roborock-ota.html

**Comment by pejotigrek** [comment]
> > I am aware that this is not a RoboRock Control Center repository
> 
> Then you're also aware that this is the wrong place for this problem. Why still do it?

ok, my bad - I phrased the question wrong. should've asked about the missing file and don't start with RRCC, sorry.

> > accidentally the file needed for update went missing
> 
> Nope. There are a few reasons for why they've been removed
> 
> * They were outdated and afaik didn't produce a working Valetudo Install
> * They were specific to some roborock models, however Valetudo runs on many more vacuums so it doesn't make sense to have that here
> * As far as I was aware, nothing was using those

as a non-programmer I couldn't know this or that - but your above points explains it clearly the reason of this files' deletion. I don't know if that file produced a working Valetudo install, as the first installation was done with your guide - I just used RRCC [which used that file] for upgrading [and also installing custom audio], as it was easier for me to click one button - and it worked fine, the installation was working as intended, no issues at all. that's just FYI, you don't need to answer about that.

thanks for the replies, looks like I touched the wrong spot - I didn't meant to - just wanted to know if the missing file is an accidental issue [in that case: hoping to be brought back] or it was on purpose. and now I know fully :)

cheers! :)
