### ISSUE TITLE
Use official Map Upload feature instead of .ppm map + slam.log

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#86]
Since there seem to be quite a few map related issues lately, I think it's time to ditch the current way of fetching the map completely. This would also enable people to disable logging without loosing map functionality.

There is a miio command which set the cloud map upload URL. Maybe there is also one which requests a refresh?

Tasks:
- Find out which commands exist
- Find out how to use them
- Add cloud upload endpoint to valetudo
- Rework map parsing to use the new format 
- Drop ppm completely?

**Comment by aluminium1** [comment]
This is probably the correct way to go forward, hopefully it's feasible

**Comment by cryptomilk** [comment]
Take a look at: https://github.com/marcelrv/XiaomiRobotVacuumProtocol/issues/8#issuecomment-461506847

**Comment by Hypfer** [comment]
Okay so the next step would be to patch dummycloud so that it responds correctly to `_sync.gen_presigned_url`?

**Comment by cryptomilk** [comment]
Yes, I guess so.

Maybe we could add support for a config file, then we could just configure the URL there. Would be easy then to change it.

**Comment by Hypfer** [comment]
https://github.com/dgiese/dustcloud/blob/master/dummycloud/src/dummycloud.c#L265

Interesting. There's already some response to that command inside dummycloud

**Comment by Bennedetto** [comment]
> Okay so the next step would be to patch dummycloud so that it responds correctly to `_sync.gen_presigned_url`?

I suggest to implement this (and the whole dummycloud) in valetudo. It is quite some work - but this will pay off, since valetudo will no longer rely on other projects to archive its core functionality (which is being independent from china-cloud).
This would enable valetudo to make use of a clean (!) map handling. It should not be that hard to implement that, since dummycloud is open-source as well - and almost everything is already reverse engeneered and documented (dummycloud sourcecode).

**Comment by h0nda** [comment]
In order to use map upload dummycloud should respond to  `_sync.batch_gen_room_up_url` with the
list of urls that corresponds to the indexes, e.g.:
Request:
```json
{ 
    "id": 135239189,  
    "method": "_sync.batch_gen_room_up_url", 
    "params": { "indexes": [ 0, 1, 2, 3 ]  } }
```
Response:
```json
    { "id": 135239189, "result": [ 
        "http://127.0.0.1:9876/robomap/0",  
        "http://127.0.0.1:9876/robomap/1",
        "http://127.0.0.1:9876/robomap/2",
        "http://127.0.0.1:9876/robomap/3"
        ]
    }
```
Every time `get_map_v1` is called it will reply either with `"retry"` or with the index. Actually anything in the URL after `robomap/` (and before `?`) will be sent as a result to `get_map_v1`. 

For example, if  URL that corresponds to index 5 looks like this:
`"https://awsde0-files.fds.api.xiaomi.com/robomap/robomap%2F118099703%2F5?GalaxyAccessKeyId=99999999999\u0026...` the reply to `get_map_v1` will be: `robomap%2F118099703%2F5`

Index `18` is used to answer to the `get_fresh_map_v1` request and `19` for the `get_persist_map_v1`. Indexes `0-17` are used by `get_map_v1`

In order `get_persist_map_v1` to return it's index `lab_status` has to be `1` and `map_save` needs to be called.

I was not able to find usage of the   `_sync.gen_presigned_url`. The URL returned in the reply to this message was never requested on the server. 

Http server needs to handle  `PUT` request to /robomap/ path. 
http heades are:
```
Accept: "*/*
Content-Length: 981
Expect: 100-continue
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
```
Request body is map compressed with gzip. Looks like it is enough to read request body without any reply.

**Comment by cryptomilk** [comment]
There are also v2 functions like `get_map_v2`

**Comment by Hypfer** [comment]
With this commit, dummycloud is now implemented within valetudo:
https://github.com/Hypfer/Valetudo/commit/276a8ef9a6afa2b449109bb40310016e2a26c220

**Comment by cryptomilk** [comment]
Does Valetudo have some logging so you can see what is going on. Sometime useful to validate that iptables is set up correctly. So answering a query and also failed queries being logged are useful in this regard.

If yes, is this documented how to enable different levels? :-)

**Comment by Hypfer** [comment]
Nope but thats a great suggestion

**Comment by Hypfer** [comment]
@h0nda how do you send `get_map_v1` since there is neither a message ID nor a stamp you can use?

**Comment by cryptomilk** [comment]
There is also a get_map_v2 command

**Comment by Hypfer** [comment]
[map.zip](https://github.com/Hypfer/Valetudo/files/3014650/map.zip)
So this is a map which got PUT using `get_map_v1`

**Comment by Hypfer** [comment]
Using each byte as an uint8 which is Used for the R value of a pixel, rendering the file on 64x64 returns this image

![image](https://user-images.githubusercontent.com/974410/55101559-a6936380-50c4-11e9-878e-d922cd9c5412.png)

This is rather pointless but its a nice image.

**Comment by cryptomilk** [comment]
I like it!  Reminds me of snake ;-)

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/55102900-b6f90d80-50c7-11e9-93da-c916d7477b27.png)


Okay this makes more sense. So this is the same graphical representation but with the whole file.
It seems like there are three chunks of data seperated by a few NUL-bytes

**Comment by Bennedetto** [comment]
Have a look here; This is the RRD format decoded;
https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/RRMapFile/RRFileFormat.md
I guess, this is a similar method.
I was able to decode the "last_map" binary from the roborock some time ago (not published the results yet, since it did not seem very useful).  This format used the header to define map dimensions (width, height) + base position (x, y), followed by a kind of occupancy map as image content.
The header variables were decoded as UInt32 (4 bytes), while the image content was decoded as a set of 4 bytes - but I was only able to decode 2 of them (laser reflection decoded in reliability per pixel [position 3] and a kind of overlays of slam [position 2] estimation how often a pixel had been scanned)..

Whatever, I guess this is a similar decoding, having a header (defining some main variables) + map (occupancy-map) + path vectors. 
How should you proceed further? Nothing easier than that:
use https://mh-nexus.de/de/hxd/ for hex representation, 
use https://www.scadacore.com/tools/programming-calculators/online-hex-converter/ to convert hex values to whatever you would like to see
use your brain to bring things together ;-)

Alternatively, (or if you do not want to take this puzzle by yourself) I suggest to generate multiple maps while driving through the room. For e.g. generate one just after the cleaning process started (close to empty map), and take maps each 10-30 seconds. 4-5 Maps should be enough to begin with reverse-engineering by having a look on the changed bytes. You might post the map-dumps here to get support :-)

**Comment by Hypfer** [comment]
It is indeed the RRFileFormat

![image](https://user-images.githubusercontent.com/974410/55107894-aa2de700-50d2-11e9-9c97-3350b16cf408.png)

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/tree/cloud_map_upload

Everything but the webinterface is done

**Comment by cryptomilk** [comment]
Awesome, did you also look into get_peristant_map_v1
