### ISSUE TITLE
Zone cleanup not working after upgrading to 2021.05.0

### ISSUE THREAD

**Issue by luke-barnett** [Hypfer/Valetudo#958]
## Describe the bug
Unable to send zone commands after upgrading to 2021.05.01

## To Reproduce

1. Open web UI
2. Click on zone
3. Select zone

### Screenshots

![image](https://user-images.githubusercontent.com/3019217/120149090-53d20b00-c23d-11eb-844e-b9a9c5187e51.png)

![image](https://user-images.githubusercontent.com/3019217/120149119-5df40980-c23d-11eb-8141-856a9156feff.png)

### Vacuum Model
Roborock S5

### Valetudo Version
2021.05.0

## Expected behavior

The vacuum starts a zone clean

## Additional context

Also doesn't work via MQTT API.

Restarted the vacuum with no sucess.

**Comment by Hypfer** [comment]
#952

> Also doesn't work via MQTT API.

Wrong.

**Comment by luke-barnett** [comment]
@Hypfer apologies, I thought searching based on the API endpoint giving a 404 would tell me if it was logged already.

I've got it all set up again by directly calling the MQTT publish commands needed. I initially assumed the MQTT API was broken as the home assistant vacuum.send_command service wasn't working and that is all auto-discovered via MQTT.

Is there an updated format to pass through the vacuum.send_command service or should I just leave it with an MQTT publish?

Thanks for all the hard work. Appreciate it.

**Comment by Hypfer** [comment]
>Is there an updated format to pass through the vacuum.send_command service

Nope. That was not reimplemented because it interfered with the vendor-agnostic mqtt rewrite. I'm sure it would've been possible somehow to accomodate for that but given that using `mqtt.publish` achives the same thing with very little changes required, the decision against it was made.

Considering the state `vacuum.mqtt` is in and how many things such as e.g. zone presets, water grade control etc don't fit in there very well or even at all, it makes more sense to ditch that and write a valetudo `custom_component` which could then provide nice `valetudo.something` services

**Comment by luke-barnett** [comment]
Interesting. Thanks for the insight.
